---
title             : "The Motivation Behind the Turnover of Korean Teachers in Terms of Working Environments"
shorttitle        : "TURNOVER MOTIVATION OF KOREAN TEACHERS"

author: 
  - name          : "Jeongim Jin"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "97401"
    email         : "jjin@email.com"
  - name          : ""
    affiliation   : ""

affiliation:
  - id            : "1"
    institution   : "Univeristy of Oregon"
  - id            : ""
    institution   : ""



abstract: |
 Job satisfaction of Korean teachers is ranked as one of the lowest among OECD countries. In addition, most research on teacher retention has focused on secondary teachers in Europe or the United States (Hong, 2010; Liu & Onwuegbuzie, 2012), this study was conducted in Seoul, South Korea by targeting public elementary school teachers. This study examined the job satisfaction of Korean elementary school teachers and its effects on their turnover motivation, particularly by looking at six variables: (1) administrative supports, (2) working conditions, (3) student disciplines, (4) decision-making participations, (5) salary and benefits and (6) collegial relationship.
  Mixed research methods were used including surveys (n= 459) and a focus group interview (n=4). By using a binary regression to look at the relationship between the six variables and turnover motivation, preliminary findings indicated that leadership and student disciplines significantly predict teachers’ turnover motivation. Specifically, if leadership and students disciplines’ scores increase, they are less likely to leave current job position (b1 = - 0.09, p< .05, b2 = - 0.07, p  < .05). These findings were supported by the interviewers stating that they are likely to demotivated when they work in hierarchical cultures, feel difficulty dealing with students, and parent requests beyond their duty and responsibilities. Given that leadership and students are more affected by school contexts than other factors examined, this result may imply that flexible organizational factors play a significant role for Korean elementary school teachers in deciding to turnover. 
  
  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "teacher turnover, teacher job satisfaction, working conditions"


bibliography      : ["r-references.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : no
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library("papaja")
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```



# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

## Material

## Procedure

## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.


# Results

# Discussion


\newpage

# References
```{r create_r-references}
r_refs(file = "r-references.bib")
```

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id = "refs"></div>
\endgroup
